### ISSUE TITLE
Variable max step height and ceiling collision

### ISSUE THREAD

**Issue by diegopau** [majikayogames/SimpleFPSController#3]
Hi.

First of all, thanks for this great starter project, very helpful.

I have a couple of questions after playing around with this a bit. I used the most recent commit:
- I see that there is a MAX_STEP_HEIGHT constant in the controller code and I tried incrementing it to for example 1.5 which I thought would allow me to climb higher stairs. However instead of that it is not able to climb the small stairs anymore. Is this a bug or the project does not intend to allow for changing that parameter?
- I tried placing a ceiling block  on top of the stairs. The expected result would be that the character goes up stairs as much as possible considering the ceiling. However, even if it is indeed able to go up the stairs even if the ceiling is there, there is a limit to this that leaves quite a lot of marging:
![just_climbing](https://github.com/user-attachments/assets/093d5d61-6aa8-4565-9973-4880957db381)
and I can in fact jump and then I can make more progress in the stairs until here:
![after jumping](https://github.com/user-attachments/assets/27893f98-e4e0-4b87-b5b2-7df15e006eb3)

My game is in third person and I have been trying to implement my own stair stepping solution with less success than you. One thing that was bothering me is that in third person I never managed to get right the smoothing out needed due to the fact that the character is basically teleporting in the Y axis. I either had camera smoothing but then you see a sudden jump in the character model/mesh from one surface to the surface of the next stair, or if the camera follows the character in real time but then is the environment (the level geometry) that suddenly moves. In your implementation for now the second thing is happening. It is not too bad because the steps are not to big compared to the size of the character.
The best implementation I have ever seen for this problem is CubeWorld implementation (CubeWorld Alpha I mean, i never tried the later version that was released in Steam) and that's what I always wanted to replicate since in my game I also have a character that has to auto climb stairs that are half of the character height. CubeWorld manages to do that fairly smoothly somehow (and it goes for the first option, camera smoothing but i feel like the character model is also a bit smoothly  moving to the next platform.
So anyway, looking forward to see if you plan to tackle this problem for third person view.

**Comment by majikayogames** [comment]
Yes MAX_STEP_HEIGHT should not be changed unless you also change the ray. The reason why it is not working is because the %StairsAheadRayCast3D is not matching the length. Usually it is slightly longer than the MAX_STEP_HEIGHT.

For the ceiling part, this is a bit of a naïve implementation in that it does not re-cast the shapecast if it hits the ceiling above and ahead. This is to save shapecasts as I have another more foolproof implementation, which I think wouldn't fail in that case, but it was like 2 or 3 more shapecasts per frame so I simplified it to this.

I didn't intend this as a perfect stair stepping solution, just one to handle most cases, probably it's still best to put a ramp where possible.

For the smoothing, yes that may just take some custom tweaking and to add camera smoothing for third person mode as well as first person. I might get around to it but no promises.

**Comment by diegopau** [comment]
Thank you for your replies, it is all clear now! modifying the %StairsAheadRayCast3D length worked perfectly.

Looking forward for future updates.
